/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gu;
import acci.TareaAcciones;
/**
 *
 * @author margv
 */
public class CrearTarea extends javax.swing.JFrame {
    static void mostrar(){
        CrearTarea crearTarea = new CrearTarea();
        crearTarea.cargarWidget();//cargar wigdet o panel
        crearTarea.setSize(700,200);
        crearTarea.setVisible(true);//para que sea visible
        crearTarea.requestFocus();// para que se vaya al frente de la pantalla
    
    }
    TareaNueva tareaNueva;

    /** Creates new form CrearTarea */
    private CrearTarea() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guardarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tareaPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear tarea");

        guardarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/saveas_1173.png"))); // NOI18N
        guardarButton.setText("Guardar");

        cancelarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel_icon-icons.com_73703.png"))); // NOI18N
        cancelarButton.setText("Cancelar");

        tareaPanel.setLayout(new javax.swing.BoxLayout(tareaPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(tareaPanel);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(guardarButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(8, 8, 8)
                        .add(cancelarButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(26, 26, 26)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(guardarButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(cancelarButton)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt){
       dispose();
   
   }
   private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt){
      TareaClass tareaClass = tareaNueva.getTareaClass();//crea la clase y la regresa
      try {
          TareaAcciones.guardarTarea(tareaClass);}
          tareas Tareas.principal.agregarTarea(tareaClass);// recibe una tarea
          dispose
      catch (SQLException ex){
          Logger.getLogger(CrearTarea.class.getName()).log(Level.SEVERE, null,ex);
      }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton guardarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel tareaPanel;
    // End of variables declaration//GEN-END:variables
    private void cargarWidget(){
        TareaNueva tareaNueva = new TareaNueva();
        tareaNueva.setSize(500,100);
        tareaNueva.setVisible(true);       
        tareaPanel.removeAll();//remover todos los componentes
        tareaPanel.add(tareaNueva);//agregar componente
        validate();//registra todos los compnentes
    }
}
